title: Romain Lacroix # your name (or website title) here
logo: "/images/avatar.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Maps, viticulture, beers, cheeses 
  <br><br>
  from France 
  <br><br>
  <a href="https://twitter.com/lacxrx">Twitter</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
